# Generated by Django 5.2.10 on 2026-04-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_notice_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='subject_specialization',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
