# Generated by Django 5.2.10 on 2026-04-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_staff_subject_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='subject_specialization',
            field=models.CharField(max_length=100),
        ),
    ]
