# Generated by Django 5.2.10 on 2026-04-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_staff_subject_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_admin_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='attended_classes',
            field=models.IntegerField(default=0, help_text='Classes attended by student'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='total_classes',
            field=models.IntegerField(default=100, help_text='Total classes conducted'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(default='Present', max_length=20),
        ),
    ]
