# Generated by Django 5.2.10 on 2026-04-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_attendance_is_admin_overridden_attendance_marked_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='feerecord',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='attended_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='marks_10th',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='marks_12th',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='marks_graduation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='total_classes',
            field=models.IntegerField(default=100),
        ),
    ]
