# Generated by Django 5.2.10 on 2026-04-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_delete_staff_feerecord_fee_amount_feerecord_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
        migrations.AddField(
            model_name='timetable',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
