# Generated by Django 5.2.10 on 2026-04-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_staff_designation_staff_joining_date_and_more'),
        ('dashboard', '0010_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile'),
        ),
    ]
