# Generated by Django 5.2.10 on 2026-04-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_timetable_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
    ]
