# Generated by Django 5.2.10 on 2026-04-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_timetable_day_of_week_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_admin_overridden',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='marked_by',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.subject'),
        ),
    ]
