# Generated by Django 5.2.10 on 2026-04-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_studentprofile_user_studentprofile_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.CharField(default='3 Hours', max_length=50)),
                ('room_no', models.CharField(max_length=20)),
            ],
        ),
    ]
