# Generated by Django 5.2.10 on 2026-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='method',
            field=models.CharField(default='Face Scan', max_length=20),
        ),
    ]
