# Generated by Django 5.2.10 on 2026-04-10 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='designation',
            field=models.CharField(default='Teacher', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='staff',
            name='leave_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='subject_specialization',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, default='Not Assigned', max_length=100, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_leaves', models.IntegerField(default=24)),
                ('used_leaves', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
