# Generated by Django 5.2.10 on 2026-04-10 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('students', '0002_remove_student_department_remove_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
    ]
