# Generated by Django 5.2.10 on 2026-04-10 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('current_semester', models.IntegerField(default=1)),
                ('total_fees', models.FloatField(default=50000)),
                ('paid_fees', models.FloatField(default=0)),
                ('roll_number', models.CharField(max_length=20)),
                ('ai_predicted_grade', models.CharField(default='Analyzing...', max_length=10)),
                ('residential_address', models.TextField(default='')),
                ('current_address', models.TextField(default='')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('parent_mobile', models.CharField(max_length=15)),
                ('tenth_marks', models.FloatField()),
                ('twelfth_marks', models.FloatField()),
                ('graduation_marks', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('OPEN', 'Open'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='OPEN', max_length=50)),
                ('is_eligible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile_main', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bonafiderequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
    ]
