# Generated by Django 5.2.10 on 2026-04-10 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_student'),
        ('fees', '0002_alter_feerecord_student'),
        ('results', '0002_alter_result_student'),
        ('students', '0002_remove_student_department_remove_student_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
