# Generated by Django 5.2.10 on 2026-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='student_faces/default_user.png', null=True, upload_to='student_faces/'),
        ),
    ]
