# Generated by Django 5.2.10 on 2026-04-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_questionbank_studentperformance_lectureswaprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Normal', 'Normal')], default='Normal', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
