# Generated by Django 5.2.10 on 2026-04-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_subject_assigned_staff_alter_timetable_staff'),
        ('staff', '0005_remove_staff_user_staffprofile_syllabusprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
